# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false
cache: packages
env:
  - PYTHON="2"
  - PYTHON="3"
  global:
    - NOT_CRAN=true
    - _R_CHECK_FORCE_SUGGESTS_=false
before_install:
  - sudo apt-get update
  - if [ $PYTHON == "3" ]; then
      sudo apt-get install python3
    fi
script:
  - |
    R CMD build .
    travis_wait 45 R CMD check --no-build-vignettes --no-manual cloudml*tar.gz
after_failure:
  - |
    cd tests
    travis_wait 45 Rscript ../.travis.R
    sleep 2
notifications:
  email:
    recipients:
      - javier@rstudio.com
    on_success: never
    on_failure: always
